/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance.Places;


public class Restaurant extends Places {
    public Restaurant(String name, int priceScore) {
        super(name, priceScore);
    }
}
