/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.HashMap;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static ArrayList<Integer> roll(int n){
        int numberOfRolls = 0;
        ArrayList<Integer> resultRoll = new ArrayList<>();
        while(numberOfRolls !=n) {
            int newRoll = (int)(Math.floor(Math.random()*6+1));
            resultRoll.add(newRoll);
            numberOfRolls++;
        }
        return resultRoll;
    }

    public static Boolean containsDuplicates(int[] inputArray) {
        HashMap<Integer, Integer> duplicateMap = new HashMap<>();
        for (int i = 0; i < inputArray.length; i++) {
            if (duplicateMap.putIfAbsent(inputArray[i], 1) !=null) {
                return true;
            }
        }
        return false;
    }

    public static double averageCalculator(int[] inputArray) {
        double average = 0.0;
        for (int i = 0; i < inputArray.length; i++) {
             average += inputArray[i];
        }
        return average/inputArray.length;
    }

    public static int[] lowestAverageArray(int[][] inputArray) {
        int index = 0;
        double avg = averageCalculator(inputArray[index]);
        for (int i = 1; i < inputArray.length; i++){
            double testingAvg = averageCalculator(inputArray[i]);
            if(testingAvg < avg){
                avg = testingAvg;
                index = i;
            }
        }
        return inputArray[index];
    }
}

