/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void lengthOfArrayMatches() {
        // Arrange
        int testRoll = 4;
        //setup sut (system under test)
        Library sut = new Library();
        //Act
        ArrayList<Integer> result = new ArrayList<>();
        result = sut.roll(testRoll);
        //Assert
        assertTrue(result.size() == testRoll);
    }

    @Test void returnCorrectBoolean() {
        Library sut = new Library();
        int[] result = {1, 2, 5, 6, 9};
        System.out.println(sut.containsDuplicates(result));
    }

    @Test void calculateAverage() {
        Library sut = new Library();
        int[] result = {2, 4, 5};
        double averageResult = sut.averageCalculator(result);
        System.out.println(averageResult);
        assertTrue(averageResult == 3.6666666666666665);
    }

    @Test void  lowestAverage() {
        Library sut = new Library();
        int[][] weeklyMonthTemperatures = {
                {5, 7, 2, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] newArr = {5, 7, 2, 65, 71, 57, 60};
        int[] result = sut.lowestAverageArray(weeklyMonthTemperatures);
        assertArrayEquals(result, newArr);
    }
}
